[build]
  command = "npm run build"
  publish = "dist"
  
[context.production]
  environment = { VITE_BACKEND_URL = "https://completeplacementrepo.vercel.app" }

# API proxying for CORS
[[redirects]]
  from = "/api/*"
  to = "https://completeplacementrepo.vercel.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/graphql"
  to = "https://completeplacementrepo.vercel.app/graphql"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://completeplacementrepo.vercel.app; connect-src 'self' https://completeplacementrepo.vercel.app https://completeplacementrepo.vercel.app/api/* https://completeplacementrepo.vercel.app/graphql; img-src 'self' data: https: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

# Cache optimization
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
  
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"